name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: ./doc.sh --full -vvv

      - name: Shellcheck
        run: find . -type f -name '*.sh' -print0 | xargs -0 shellcheck

  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: ./doc.sh --full -vvv
