name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
      - name: Shellcheck
        run: find . -type f -name '*.sh' -print0 | xargs -0 shellcheck
