name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          mkdir -p ~/.config/gh
          echo "user: fakeuser" >> ~/.config/gh/hosts.yml
          mkdir -p ~/code/fakeuser
          git clone https://github.com/lewagon/dotfiles ~/code/fakeuser/dotfiles

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: GITHUB_CI=1 ./doc.sh --full -vvv

      - name: Shellcheck
        run: find . -type f -name '*.sh' -print0 | xargs -0 shellcheck

      - name: Doctor should be non interactive
        run: |
          if grep -v "while.*read" doc.sh | grep -nE '^[^#]*(;|^| )*read($|;| )';
          then
            echo "Error: found use of read keyword. The doctor should be non interactive";
          fi

  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          mkdir -p ~/.config/gh
          echo "user: fakeuser" >> ~/.config/gh/hosts.yml
          mkdir -p ~/code/fakeuser
          git clone https://github.com/lewagon/dotfiles ~/code/fakeuser/dotfiles

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: GITHUB_CI=1 ./doc.sh --full -vvv
