name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          mkdir -p ~/.config/gh
          echo "user: fakeuser" >> ~/.config/gh/hosts.yml
          mkdir -p ~/code/fakeuser
          git clone https://github.com/lewagon/dotfiles ~/code/fakeuser/dotfiles

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: GITHUB_CI=1 ./doc.sh --full -vvv

      - name: Check doctor age
        run: ./scripts/doc_age.sh || { echo "Update LAST_DOC_UPDATE variable or run ./scripts/update.sh"; exit 1; }

      - name: Check wanted versions
        run: ./scripts/check_wanted_versions.sh

      # - name: Run docker tests
      #   run: ./test/test.sh

      - name: Shellcheck
        run: find . -type f -name '*.sh' -print0 | xargs -0 shellcheck

      - name: Error and warning format
        run: |
          if grep -i 'error "Error' doc.sh  | grep -qv 'error "Error: '
          then
            echo "Error: wrong error messages found"
            echo "       the format has to be 'error \"Error: message'"
            echo "       if that is not matched the error counting breaks"
            echo ""
            echo ""
            grep -i 'error "Error' doc.sh  | grep -v 'error "Error: '
            exit 1
          fi
          if grep -i 'warn "Warning' doc.sh  | grep -qv 'warn "Warning: '
          then
            echo "Error: wrong warning messages found"
            echo "       the format has to be 'warn \"Warning: message'"
            echo "       if that is not matched the warning counting breaks"
            echo ""
            echo ""
            grep -i 'warn "Warning' doc.sh  | grep -v 'warn "Warning: '
            exit 1
          fi

      - name: Doctor should be non interactive
        run: |
          if grep -v "while.*read" doc.sh | grep -nE '^[^#]*(;|^| )*read($|;| )';
          then
            echo "Error: found use of read keyword. The doctor should be non interactive";
            exit 1
          fi

  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          mkdir -p ~/.config/gh
          echo "user: fakeuser" >> ~/.config/gh/hosts.yml
          mkdir -p ~/code/fakeuser
          git clone https://github.com/lewagon/dotfiles ~/code/fakeuser/dotfiles

      - name: Run the doctor
        run: ./doc.sh

      # - name: Run the doctor (curl web)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course web

      # - name: Run the doctor (curl data)
      #   run: curl -s https://raw.githubusercontent.com/ElvisDot/lewagon-setup/master/doc.sh | bash -s -- --course data

      - name: Run the doctor (full/verbose)
        run: GITHUB_CI=1 ./doc.sh --full -vvv
